
version: '3.7'

services:

  mongos:
    networks:
      - mongo
    container_name: mongos
    image: mongo
    command: mongos --configdb cfgrs/cfgsvr1:27017,cfgsvr2:27017,cfgsvr3:27017 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 60000:27017

networks:
    mongo:
        name: mongo
        driver: bridge
