
version: '3.7'

services:

  shard2svr1:
    container_name: shard2svr1
    networks:
      - mongo
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 50004:27017
    volumes:
      - shard2svr1:/data/db

  shard2svr2:
    container_name: shard2svr2
    networks:
      - mongo
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 50005:27017
    volumes:
      - shard2svr2:/data/db

  shard2svr3:
    container_name: shard2svr3
    networks:
      - mongo
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 50006:27017
    volumes:
      - shard2svr3:/data/db

volumes:
  shard2svr1: {}
  shard2svr2: {}
  shard2svr3: {}

networks:
    mongo:
        name: mongo
        driver: bridge
